language: java
dist: trusty
jdk:
  - openjdk8
env:
    global:
      # GPG_KEYNAME=...
      - secure: "V3sLeCMppDGMZHZVc0q1Pl3GiGU6YRM8DnFNXj/RdO0EG9L2gCyDOo+CyF2ipwBdLEmOQxRNQZvGNUN7g/UTZwXtHWU56a6hXDEG7wjxsJ97FkKgfML1ItHuGukEykJl+Pb8qxRp65Mi7tybVd9th3zDbY406j+yfLbRqrOev/2ik7+0WOC0mixI78J7P3vY10Ka6i2GfoqSNiX6LVW3LPc0KX6u+3xCRw7UG/TQkoHjTjQCx/lLEyhLGXSF4N9+zpWPQJtG0zlepcgGXFPAtCodHEh+NPTnxbj3e9QpaFfhmKo5ZJ0oFypkX7bhwXyJaEthXT4uycuXqyWIB+buuidEPVdV9t/YT//gS/1lHqmhJEq/PT/DfdSt1+C/Om22IG2maokEtX/6y4JLDIE/pXdUnsY9tp6De4r4o4XRFqURTR9REMoWeyU93BPtGbKJDg6kCOiLlrKCo0B/cjsQVnNrH2iPMz/yWHzvO0Cu8rYL3OtxkGOTnBNA/9Htn4N9ZkaMFkjcHmgsajiZG8eulKzdbGLjAzxnw/9BkCi1lDDFXYGJvilT6x5Gcp5wsAQ6Rlg7WcbRNadrEPlU9hrIiP/Lora3whJAGBKWAyzxKbIcLqQtEwIQC7owLpw4wnhCgrQgq+PIZQmNgpy5j3JH/wtzkcaxn1MlEmTVG0nGSyk="
      # GPG_PASSPHRASE=...
      - secure: "PepT+X7JEwlFmY8TqOCGa82Qx/x71p0XdASzbf4HLTycKyF7uz/iRhsq4443DPN8kET77GJXqUXaW7+db4gRaaORaKLBCvPZPGKygjQHE4EXeiDM4fwG9D0HjOsUD4VGZG6hl/I7kZOKJNbcbrvz+HM5BMtPsi8dEZQ8/0d7K/TvL/jmgVUdYZUwd7/c6eaBBLY4Ar2kJ352EF7D2pLw4J7XaCed1w0qw6Ur8snIEp4/AcTQSTCTqH5Z9aR3417jFChh1yorhOppV+0z/GZJLsbyVHlUeh26OeTfMTneWh84wtexqfwN07ygB61DTzJtyKefxtulLGJL34EDhiTR6MLo7XmoCYkA4YJURcZgkrK083vJ5gVOHPrdnDC3kszyBY0SQzome6MZtIZ6VUcbr0qjHVKK4ObkIjhxj34hmrCG7TCydcTmOoS4E4/EX06AubCMEBqu5enrZMTEoTSDGZGjFs9McFqB8Wyf8+bsuZfwI16pLVlH88sSwiA7N3aPXDwJThIa27EF9HTPVyAW2c5Y9n5dQWJqmPccQofnVdjP3gN7m24VYJunFX4tzueKYnBcPLoPzUM7+jZVtVL90DYlLMlT2h/Aoz4/VJqzkor8SI5cAjnu/rsIzuiuD4ti0kK7kgMNDHCebMK/P0x9CjF+RKB297eSDVd5bc9oGuw="
      # SONATYPE_USER=...
      - secure: "KvK2Rx/BgfnoFzpesHT9BfoB7XRx3RGRJgv2rLDTl+T3dkfYyVUw+j6b8nvl0WH8xZEVWkFp+AohdS9/HZ2u2uKArsJ6o1+Jb24vWElf/fCwHX0yMSuZIX3h5oqXYGAIcCP+QftXLLjbGgr+g650uiKUqD7mmHQtXbBvGDVyIdlT3cLnhOrb7mhQuaLxmaxZc/7JmJb7NSd1vCCI1lev+XgeO6MVgTV7QIJhyjFuYsQFcnwyXyrCi6UMxxLl6G3p4KpXe8/VF5JvhvnXHvTDp/PeB8yIpAJrDFxGYQtoSMr8X+Y3hTGsg5hK2EF0/2S5f4jpdOR7IZ0s8gA9U1rY69FEv2XUSYZNWxAFEAKHvrkAT0UbgFj3jQhRBkXtAVpbk9hdS70hfQikmu3csuChQGbi9a2geSlPLzq8vsuCwgkGQ+GTUwkXd4NKrsz/M+PhubNLxlOLEy2PC3HuB6SjB/dZ39LTacgOuzuifcVdIqkDvpYfnjUrTfpav5P5AXVr/yHe2DAvEpe6heyN6Ah3/6gmJUbl2zWfsQjeVEX1u7n+zcWZIbnC8sJY7hgjZKkZ7z8kcFPpfZcGP5cnwd4tkVRN2QFNFTrzVun8FENrdVzj41KuHwthMcryaS1QPDgiTNjOTPG7U2iImWJbpGtQcMm29GRLW/8OQT3TOj9QH5E="
      # SONATYPE_PASSWORD=...
      - secure: "SO4zuxKqGhYL11LL2IZ4e4yffFZyvEDueN/otFs69YhXJ1Ylknn6uy5DvwzyHqU0zvQ3IzwEdCpxKlUV8SP2m7Uvh4zhfB89hYwVtkAzOlqFERPHbDn3uP4O5UIDvFoGFvAp2OkFUeZqtGfC6X3iAdm+az2XGf6vzzcSuJn1O5+EgiO/Hqv14BJR2OyuMn9US7nlYAueek5UdbMYuTFJTgVtx+EBopbBZ96mKGinYCKGfnSdTMUHeygcGF00qPSkL9YNV49EV0GTgkr+Y6BRLgIU15mqBkHq0/A8equsV3MHCGW8HcKOwWGBoukH8VYaRSlsKIJjnmO7bFH8WjrgFmxWrtNGlLh40wsgvrv9XD7edXYS5rJocP4uFq2WVqCS3C1VqV89wvzcnnJ0ozBg0doqwnsK2sUdESqroQMkYIZFi3KepSZ3S9K862EQ6RcMV6rOeVLwdI2Sv/TC33Xlh7hvk62tyb4FB8PsPC4H/q+9o9rQlFJGGIhxR+IQCXZSzfr2wovdVzH33W3SHLbxv1RA4dMPZAvGCTI6m9AEPWtQW08H7XEi8Aq1Gd3sYQrPbM3Pe+Dg+EJD32Hluu7emiu0DQHQw7D2Om3InQ954km3mHyCIQePcUGhphkHfrZAAHIqSInT/ekftDSnUmZzf6+mfPzdJ7BXuiOtoxn7cWU="

install:
  - openssl aes-256-cbc -K $encrypted_b8a72b3bd474_key -iv $encrypted_b8a72b3bd474_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar

script:
- if [[ ! -z $TRAVIS_TAG ]]; then mvn versions:set -DnewVersion=$TRAVIS_TAG; fi
- mvn -B -Ptravis --settings .m2/settings.xml clean deploy

cache:
  directories:
  - "$HOME/.m2/repository"

